### ISSUE TITLE
Uncaught ReflectionException: Class "HeimrichHannot\EncoreContracts\PageAssetsTrait" not found

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-tab-control-bundle#6]
**Context**
Contao version: 4.13.40
Bundle version: 1.2.0
PHP version: 8.1

**Description**
Bei einer Paketaktualisierung (vorher war das Bundle in Version 1.1.0 installiert) kommt es im Nachgang zu einem fatal error, siehe Stack trace.
Bei einem vorherigen composer update dry-run hatte es keine Fehler gegeben.
Ich musste die composer.lock aus dem Backup einspielen, um die Installation wieder zu reanimieren.

```
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "HeimrichHannot\EncoreContracts\PageAssetsTrait" not found while loading "HeimrichHannot\TabControlBundle\Asset\FrontendAsset". in /var/www/vhosts/contao4/vendor/composer/ClassLoader.php:495
Stack trace:
#0 [internal function]: Composer\Autoload\ClassLoader->loadClass('...')
#1 /var/www/vhosts/contao4/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('...')
#2 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/ContainerBuilder.php(370): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#3 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/FileLoader.php(217): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('...')
#4 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/FileLoader.php(105): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('...', '...', Array, Object(Symfony\Component\DependencyInjection\Compiler\RegisterAutoconfigureAttributesPass))
#5 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(699): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), '...', '...', NULL)
#6 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(256): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinition('...', Array, '...', Array, false, true)
#7 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(176): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinitions(Array, '...')
#8 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(132): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadContent(Array, '...')
#9 /var/www/vhosts/contao4/vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('...', NULL)
#10 /var/www/vhosts/contao4/vendor/heimrichhannot/contao-tab-control-bundle/src/ContaoManager/Plugin.php(44): Symfony\Component\Config\Loader\DelegatingLoader->load('...')
#11 /var/www/vhosts/contao4/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(167): HeimrichHannot\TabControlBundle\ContaoManager\Plugin->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader), Array)
#12 /var/www/vhosts/contao4/vendor/symfony/dependency-injection/Loader/ClosureLoader.php(39): Contao\ManagerBundle\HttpKernel\ContaoKernel->Contao\ManagerBundle\HttpKernel\{closure}(Object(Contao\ManagerPlugin\Config\ContainerBuilder), '...')
#13 /var/www/vhosts/contao4/vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\ClosureLoader->load(Object(Closure), NULL)
#14 /var/www/vhosts/contao4/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(189): Symfony\Component\Config\Loader\DelegatingLoader->load(Object(Closure))
#15 /var/www/vhosts/contao4/vendor/symfony/http-kernel/Kernel.php(649): Contao\ManagerBundle\HttpKernel\ContaoKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader))
#16 /var/www/vhosts/contao4/vendor/symfony/http-kernel/Kernel.php(545): Symfony\Component\HttpKernel\Kernel->buildContainer()
#17 /var/www/vhosts/contao4/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(295): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#18 /var/www/vhosts/contao4/vendor/symfony/http-kernel/Kernel.php(789): Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()
#19 /var/www/vhosts/contao4/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#20 /var/www/vhosts/contao4/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#21 /var/www/vhosts/contao4/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#22 /var/www/vhosts/contao4/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/vhosts/contao4/vendor/contao/manager-bundle/bin/contao-setup(44): Symfony\Component\Console\Application->run()
#24 /var/www/vhosts/contao4/vendor/bin/contao-setup(119): include('...')
#25 {main} in /var/www/vhosts/contao4/vendor/heimrichhannot/contao-tab-control-bundle/src/Asset/FrontendAsset.php on line 14
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
```

**Comment by koertho** [comment]
Oh, da fehlt nur eine Dependency, fixe ich gleich :)

**Comment by koertho** [comment]
Behoben in 1.2.1.

**Comment by rustykowski** [comment]
großartig, vielen Dank!
